### ISSUE TITLE
Support AWS::RDS::DBInstance and AWS::RDS::DBCluster

### ISSUE THREAD

**Issue by a2ush** [awslabs/diagram-as-code#102]
## Issue
Currently,  awsdac does not support AWS::RDS::DBInstance and AWS::RDS::DBCluster types.
```
$ awsdac template.yaml -v
...
WARN[0000] Unknown type: AWS::RDS::DBCluster
WARN[0000] Unknown type: AWS::RDS::DBInstance 
```

### Note/Workaround

You can use `AWS::RDS` in your template.
https://github.com/awslabs/diagram-as-code/blob/642d911bc7d3742b91426b9d101c6258f327ef1a/definitions/definition-for-aws-icons-light.yaml#L2914-L2923

**Comment by a2ush** [comment]
```
Resources:
  Aurora:
    Type: AWS::RDS::DBCluster
  DB:
    Type: AWS::RDS::DBInstance
```
![image](https://github.com/awslabs/diagram-as-code/assets/41433979/a57092be-b657-44ca-b4ca-894eeeef6b2a)
