### ISSUE TITLE
Describe how to change icons in DAC file

### ISSUE THREAD

**Issue by a2ush** [awslabs/diagram-as-code#106]
## Request

 * Update [introduction guide](https://github.com/awslabs/diagram-as-code/blob/main/doc/introduction.md) to explain how to change icons

### Detail

When you set "preset" parameter in DAC file,  you can change icons based on your wants.
```
Diagram:
  DefinitionFiles:
    - Type: URL
      Url: "https://raw.githubusercontent.com/awslabs/diagram-as-code/main/definitions/definition-for-aws-icons-light.yaml"
  Resources:
    S3:
      Type: AWS::S3
```
![image](https://github.com/awslabs/diagram-as-code/assets/41433979/c4531e51-754b-4323-8ece-325d61788922)

```diff
Diagram:
  DefinitionFiles:
    - Type: URL
      Url: "https://raw.githubusercontent.com/awslabs/diagram-as-code/main/definitions/definition-for-aws-icons-light.yaml"
  Resources:
    S3:
      Type: AWS::S3
+     Preset: "Bucket with objects"
```
![image](https://github.com/awslabs/diagram-as-code/assets/41433979/7196ca69-5292-4233-9b7d-9d2ae79487d7)

**Comment by WahidX** [comment]
But how to import custom icons?
I have added a new definition along with the default one,
```yaml
Definitions:
  svca:
    Type: Resource
    Icon:
      Path: './icons/svca.png'
    Label:
      Title: 'TITLE'
    Border:
      Color: 'rgba(0, 0, 255, 255)'

  svcb:
    Type: Resource
    Icon:
      Path: ./icons/svcb.png
    Label:
      Title: 'TITLE'
    Border:
      Color: 'rgba(0, 0, 0, 255)'
```

The generated diagram does have the service with label but no icons are attached.
I have tried with different res of the icons, 50x50, 150x150 and even more. Can that be elaborated a bit?
