### ISSUE TITLE
AWS::Region should support Title

### ISSUE THREAD

**Issue by mattburgess** [awslabs/diagram-as-code#112]
**Is your feature request related to a problem? Please describe.**

Other group types allow a `Title` to be provided, but `AWS::Region` doesn't appear to.

**Describe the solution you'd like**

The following definition...

```yaml
  Region:
  Type: AWS::Region
  Title: "us-east-1 (N. Virginia)"
  Children:
    - VPC1
```

...should result in a Region group box with the title `us-east-1 (N. Virginia)` displayed in the same location as other group box's titles do.

**Describe alternatives you've considered**

**Additional context**

On a diagram with an architecture showing regional HA/failover capability between 2 regions in the same account, it would be useful if the 2 regions could be clearly marked.
