### ISSUE TITLE
Allow adding labels / titles to links

### ISSUE THREAD

**Issue by mikicz** [awslabs/diagram-as-code#142]
**Is your feature request related to a problem? Please describe.**
In some diagrams I'd find it useful what a link means / does, say for example "HTTP request doing X" when linking one ECS Service to another ECS Service

**Describe the solution you'd like**
Add a property called `Title` to the link definition, or a nested `Label` with property `Title` (to allow for further properties around the label)
For example:
```
    - Source: ALB # (required)
      SourcePosition: NNW # (required)
      Target: PublicSubnet1Instance # (required)
      TargetPosition: S # (required)
      Title: Description
```

or 

```
    - Source: ALB # (required)
      SourcePosition: NNW # (required)
      Target: PublicSubnet1Instance # (required)
      TargetPosition: S # (required)
      Label: 
          Title: Description
```

**Describe alternatives you've considered**
I've colour schemed my links and then in the text I refer to links by colour.
