### ISSUE TITLE
Control point of Link

### ISSUE THREAD

**Issue by ugwis** [awslabs/diagram-as-code#174]
Adding control points when linking allows you to skip links of the same style or implement curves in the future.

Proposal
```
    # VPN
    - Source: CGW
      SourcePosition: N
      Target: VGW
      TargetPosition: S
      Type: orthogonal
      ControlPoints:
      - Resource: VPN
        Position: N
```
