### ISSUE TITLE
Create mappings for CloudFormation resource types

### ISSUE THREAD

**Issue by ugwis** [awslabs/diagram-as-code#20]
Need to create a correspondence between CloudFormation resource types and architecture icons' labels (preset names).
Currently, We are using [this file](https://github.com/awslabs/diagram-as-code/blob/main/tools/make-definition-from-pptx-mappings) to list the corresponding resource types. 

## workaround
You can also use resource types that are not currently defined by utilizing a preset with the same name as the icon label.
```
Diagram:
  DefinitionFiles:
    - Type: URL
      Url: "https://raw.githubusercontent.com/awslabs/diagram-as-code/main/definitions/definition-for-aws-icons-light.yaml"
  Resources:
    Canvas:
      Type: AWS::Diagram::Canvas
      Direction: vertical
      Children:
        - StepFunction
    StepFunction:
      Type: AWS::Diagram::Resource
      Preset: "AWS Step Functions"
```
You can check the preset name in the icon label of the [pptx file](https://aws.amazon.com/architecture/icons/) or in the [definition file](https://github.com/awslabs/diagram-as-code/blob/main/definitions/definition-for-aws-icons-light.yaml).
