### ISSUE TITLE
Generate diagrams from CF templates

### ISSUE THREAD

**Issue by moltar** [awslabs/diagram-as-code#9]
Would it be possible to generate diagrams from the templates?

Perhaps could use tags for things that CF does not support directly.

And then can use resource properties to infer some of the information for the diagrams (e.g. titles).

This would then be great for use with CDK, where resources can be defined and tagged in code, and then a template is generated and then a diagram is generated from that.

**Comment by ugwis** [comment]
Thank you for creating issue!

Currently, it is not supported, but it is within our scope. There are a few challenges we will need to overcome in order to achieve this:
- Create a CloudFormation resource type mapping: We are currently using [this file](https://github.com/awslabs/diagram-as-code/blob/main/tools/make-definition-from-pptx-mappings) to create a list of resource types that correspond to the icon titles in the pptx file.
- Resolve resource dependency of templates: To generate diagrams, dependencies should be resolved by parsing the DependsOn, Ref, and Sub functions as shown in [this](https://github.com/awslabs/diagram-as-code/blob/main/doc/static/dependency-graph.png). However, resolving conditions that depend on parameters is difficult. Resolve conditions only to the extent possible, or use an interactive shell and let the user specify it.
- Must be customizable and consider for non-CloudFormation users. Resources have several attributes to customize the diagram layout/decoration.
   https://github.com/awslabs/diagram-as-code/blob/0fb7005ca7d1fd3e27b9bd16f302e2862902239b/cmd/awsdac/main.go#L45-L54
   For example, CloudFormation users may be easier to use the following notation:
   ```
   Resources:
     Instance:
       Type: AWS::EC2::Instance
       Properties:
         KeyPair: 
         ...
       Metadata:
         Diagram:
           Title: Instance 1
   Metadata:
     Diagram:
       DefinitionFiles:
         ...
   ```
   However, for non-CloudFormation users, unnecessary Metadata will be required to utilize custom attributes, as demonstrated in the following example.
   ```
   Resources:
     Instance:
       Type: AWS::EC2::Instance
       Metadata:
         Diagram:
           Title: Instance 1
   Metadata:
     Diagram:
       DefinitionFiles:
         ...
   ```
   One possible solution is to make the current notation coexist with the CloudFormation notation. I'm not sure if this method would be supported by the community. Please let me know if you have any other good ideas.

To give some background, I have dozens of CloudFormation templates and created this tool to generate diagrams for these templates. It seems that many users are looking forward to generation from CloudFormation templates, so I would be happy if I could contribute with this tool.
