### ISSUE TITLE
Support AWS::CodePipeline::Pipeline

### ISSUE THREAD

**Issue by a2ush** [awslabs/diagram-as-code#92]
Currently, you need to define "AWS::CodePipeline" as a ResourceType when you want to describe "CodePipeline" in a diagram.
However, the resource type of CloudFormation does not this type.
And "AWS::CodePipeline::Pipeline" should also have children (e.g. CodePipeline maybe has CodeCommit repo or CodeBuild project..).

AWS::CodePipeline::Pipeline - AWS CloudFormation
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html

diagram-as-code/definitions/definition-for-aws-icons-light.yaml at main · awslabs/diagram-as-code · GitHub
https://github.com/awslabs/diagram-as-code/blob/main/definitions/definition-for-aws-icons-light.yaml#L945C3-L954
```
  AWS::CodePipeline:
    Type: Resource
    Icon:
      Source: ArchitectureIconsPptxMedia
      Path: "image644.png"
    Label:
      Title: "AWS CodePipeline"
      Color: "rgba(0, 0, 0, 255)"
    CFn:
      HasChildren: false
```
