### ISSUE TITLE
Use shortened service names as the default for AWS services

### ISSUE THREAD

**Issue by a2ush** [awslabs/diagram-as-code#94]
## Detail
Currently, awsdac describes service full-names by default.
Related to this behavior, awsdac has the following issue https://github.com/awslabs/diagram-as-code/issues/67.

From the perspectives of visibility and widespread usage, it would be better to use the shortened service names as the default.

### Note
You can change the name by defining "Title" param in the template.
```
Diagram:
    ...
    Resources:
        ...
        ECSCFntest:
            Type: AWS::ECS::Cluster
            Title: "ECS(backend)"
```
![image](https://github.com/awslabs/diagram-as-code/assets/41433979/de66bd32-f436-4133-91ba-4db214c2c01a)
